@csharp_webapi_mysql_HostAddress = http://localhost:5099

GET {{csharp_webapi_mysql_HostAddress}}/Person
Accept: application/json

###
POST {{csharp_webapi_mysql_HostAddress}}/Person
Content-Type:application/json

{
    "codigo":12,
    "nome": "Danilo lopes",
    "cidade":"belem",
    "idade": 20
}

