@csharp_webapi_mysql_HostAddress = http://localhost:5099

GET {{csharp_webapi_mysql_HostAddress}}/Person
Accept: application/json


###
GET {{csharp_webapi_mysql_HostAddress}}/Person/1
Accept: application/json

###
POST {{csharp_webapi_mysql_HostAddress}}/Person
Content-Type:application/json

{
    "nome": "Teste validation",
    "cidade":"belem",
    "cidade":"aa",
    "idade": 20
}

###
PUT  {{csharp_webapi_mysql_HostAddress}}/Person/1
Content-Type:application/json

{
    "nome": "Karma Atualizado mano",
    "idade": 16,
}

###
DELETE  {{csharp_webapi_mysql_HostAddress}}/Person/10
Content-Type:application/json
